table 'ai_recommendations'

	column 'RecommendationID'
		dataType: int64
		sourceColumn: RecommendationID

	column 'Title'
		dataType: string
		sourceColumn: Title

	column 'Insight'
		dataType: string
		sourceColumn: Insight

	column 'ActionableAdvice'
		dataType: string
		sourceColumn: ActionableAdvice

	column 'Priority'
		dataType: string
		sourceColumn: Priority

	column 'ImpactArea'
		dataType: string
		sourceColumn: ImpactArea

	measure 'Total Recommendations' = COUNTROWS('ai_recommendations')

	measure 'High Priority Recommendations' = CALCULATE([Total Recommendations], 'ai_recommendations'[Priority] = "High")

	partition 'ai_recommendations' = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\\Projects\\anlytics-projects\\AI-Powered Resume & Hiring Analytics-pb1\\HR-Analytics-Dashboard\\data\\processed\\ai_recommendations.xlsx"), null, true),
			    Data = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
			    PromotedHeaders = Table.PromoteHeaders(Data, [PromoteAllScalars=true]),
			    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {{"RecommendationID", Int64.Type}, {"Title", Text.Type}, {"Insight", Text.Type}, {"ActionableAdvice", Text.Type}, {"Priority", Text.Type}, {"ImpactArea", Text.Type}})
			in
			    TypedColumns

