table 'dim_department'

	column 'Department'
		dataType: string
		sourceColumn: Department

	column 'AvgSalary'
		dataType: double
		sourceColumn: AvgSalary

	column 'HeadCount'
		dataType: int64
		sourceColumn: HeadCount

	column 'DepartmentID'
		dataType: int64
		sourceColumn: DepartmentID

	partition 'dim_department' = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\\Projects\\anlytics-projects\\AI-Powered Resume & Hiring Analytics-pb1\\HR-Analytics-Dashboard\\data\\processed\\dim_department.xlsx"), null, true),
			    Data = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
			    PromotedHeaders = Table.PromoteHeaders(Data, [PromoteAllScalars=true]),
			    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {{"Department", Text.Type}, {"AvgSalary", Number.Type}, {"HeadCount", Int64.Type}, {"DepartmentID", Int64.Type}})
			in
			    TypedColumns

